---
pagetitle: MetaVoice About
---
```{r child='assets/setup.Rmd'}
```

```{r echo=FALSE}
menuNavbar()
```

```{r echo=FALSE}
people <- yaml::yaml.load_file(here("metadata", "people.yaml"))

renderMemberInfo <- function(memberInfo) {
  div(class = "box-pad",  
    shinydashboard::box(class = "box-content", width = NULL, align = "center", #status = "danger",
      solidHeader = TRUE, 
      img(src = memberInfo$image, width = 180, height = 180),
      a(h4(strong(memberInfo$name)), href = memberInfo$website, target = "_blank"),
      memberInfo$affiliation,
      br(),
      if (!is.null(memberInfo$email)) a(memberInfo$email, href = sprintf("mailto:%s", memberInfo$email)),
      br(),
      tags$small(
        map(unlist(strsplit(if (is.null(memberInfo$databases)) {""} else {memberInfo$databases}, ", ")),
          ~list(code(.x, class = "red-code"), br())) %>%
        flatten()
        )
      )
    )
  }

renderGroupMembers <- function(memberStatus, peopleSet) {
  fullWidthPanelBox(memberStatus, purrr::map(peopleSet, renderMemberInfo))
}

tagList(map(names(people), ~renderGroupMembers(., people[[.]])))

fullWidthPanelBox(
  "MetaLab",
  HTML("This website was built on the basis of the code provided by the MetaLab team, which can be found 
    <a href='https://github.com/langcog/metalab2'>on GitHub</a>. Thank you for sharing your code, knowledge and ideas.")
)

fullWidthPanelBox(
  "Source code",
  HTML("The source2 for this website can be found <a href='https://github.com/LNJ-ND/MetaVoice_Website'>on GitHub</a>. The website itself is hosted through GitHub Pages, with the accompanying visualizations hosted through <a href='https://www.shinyapps.io'>shinyapps.io</a>.")
)
```

```{r, echo=FALSE}
htmltools::includeHTML("footer.html")
```
