---
pagetitle: MetaVoice Analyses
---
```{r child='assets/setup.Rmd'}
```

```{r echo=FALSE}
shinyapps <-  yaml::yaml.load_file(here("metadata", "shinyapps.yaml"))
#reportList <- yaml::yaml.load_file(here("metadata", "reports.yaml"))
menuNavbar()
```

```{r echo=FALSE}
# function to render application boxes 
renderApplication <- function(appInfo) { 
  box(width = 4, align = "center", style = "font-size: 125%; display: block; float: center;",
    tagList(
      a(href = paste0("app.html?id=", unlist(appInfo)["id"]),
        unlist(appInfo)["title"], #style="color:black",
        br(),
        img(class = "app-image",
          src = unlist(appInfo)["image"], width = 270, height = 200)
        )
      )
    )
}

renderDomainApplications <- function(domainName, applications) { 
  fullWidthPanelBox(domainName, purrr::map(applications, renderApplication))
}

# shiny ui to display the boxes
fluidRow(
  column(width = 12,
    names(shinyapps) %>%
    purrr::map(~ renderDomainApplications(., shinyapps[[.]]))
    )
  )
```

```{r echo=FALSE}
# for reports: currently not avialble on metavoice
# renderReport <- function(reportName, reportLink) { 
#   column(width = 3, align = "center",
#     div(class = "well well-sm",
#       p(class = "report-well",
#         tags$a(href = reportLink, reportName)
#       )
#     )
#   )
# }
# 
# fluidRow(
#   column(width = 12,
#          fullWidthPanelBox("Reports", reportList %>% purrr::map(~ renderReport(.$title ,paste0("reports/", .$id,"-outer.html"))))
#     )
#   )
```

```{r, echo=FALSE}
htmltools::includeHTML("footer.html")
```


