---
pagetitle: dataset-template
params:
  dataset_info: !r NULL
  dataset_raw: !r NULL
---

```{r child='assets/setup.Rmd'}
```

<style>.dt-buttons.btn-group {float:left;}</style>

```{r echo=FALSE, warning=FALSE, message=FALSE}
if (is.null(params$dataset_info) || is.null(params$dataset_raw)) {
  knitr::knit_exit()
}

dataset_raw <- params$dataset_raw
dataset_info <- params$dataset_info
## what is this attempting to do?
## dataset_raw <- dataset_raw[colSums(!is.na(dataset_raw)) > 0]

rowCallback <- c(
    "function(row, data){",
    "  for(var i=0; i<data.length; i++){",
    "    if(data[i] === null){",
    "      $('td:eq('+i+')', row).html('NA')",
    "        .css({'color': 'rgb(151,151,151)', 'font-style': 'italic'});",
    "    }",
    "  }",
    "}"  
  )

```

```{r echo=FALSE}
menuNavbar("../")
```

```{r results='asis', echo=FALSE}
fluidRow(
  column(width = 12,
    h1(dataset_info$name),
    tags$ul(
      if (dataset_info$citation != "") {
        if (dataset_info$link == "") {
          tags$li(dataset_info$citation)
        } else {
          tags$li(a(href = dataset_info$link, dataset_info$citation))
        } 
      } else {
        NULL
      },
      tags$li(
        paste0(
          "N papers = ", as.integer(dataset_info$num_papers),
          ", N experiments = ", as.integer(dataset_info$num_experiments),
          ", N participants = ", as.integer(dataset_info$num_subjects)
          )
        ),
      tags$li(dataset_info$short_desc),
      tags$li(paste("Curator is", dataset_info$curator)),
      tags$li(strong("Search Strategy:"), dataset_info$search_strategy),
      tags$li(strong("Systematic:"), if(!is.null(dataset_info$systematic) && dataset_info$systematic) "yes" else "no"))
    ))
```

```{r echo=FALSE, warning=FALSE}
fluidRow(
  br(), 
  column(width = 12,
    tabBox(width = 12,
      tabPanel(strong("Data"),
        DT::datatable(
          class = 'cell-border stripe',
          height = "auto",
          select(dataset_raw, -long_cite, -dataset, -short_name),
          fillContainer = FALSE,
          width = "100%",
          style = "bootstrap",
          rownames = FALSE,
          extensions = c('Buttons', 'FixedColumns'),
          options = list(scrollX = TRUE, autoWidth = TRUE, pageLength = 20,
                         columnDefs = list(list(width = '200px', targets = c(2,5,7,15))),
            dom = 'Bfrtip',
            buttons = list(
              'print',
              list(
                extend = 'collection',
                buttons = list(
                  list(extend='csv', filename = dataset_info$short_name),
                  list(extend='excel', filename = dataset_info$short_name)),
                text = 'Download')
              ),
            fixedColumns = list(leftColumns = 2),
            rowCallback = JS(rowCallback)
      )
    )),
      tabPanel(strong("Papers"),
        purrr::map(unique(dataset_raw$long_cite), ~ tagList(p(.)))
      )
    )
  )
)



```

```{r, echo=FALSE}
htmltools::includeHTML("footer.html")
```

<script>
$('.tab-pane > div').css("width", '100%');
</script>
